In [ ]:
email = "Félicitations, vous avez gagné un cadeau gratuit"
label = 1
print("Email :", email)
print("Label :", label)
mots_cles = ["gratuit", "gagné", "bonjour", "rapport"]
print("Mots observés :", mots_cles)
vecteur_email = []
for mot in mots_cles:
    if mot in email.lower():
        vecteur_email.append(1)
    else:
        vecteur_email.append(0)
print("Vecteur numérique :", vecteur_email)


Email : Félicitations, vous avez gagné un cadeau gratuit
Label : 1
Mots observés : ['gratuit', 'gagné', 'bonjour', 'rapport']
Vecteur numérique : [1, 1, 0, 0]


In [ ]:
import numpy as np
emails = [
    ("gagnez mille euros gratuit", 1),
    ("bonjour réunion demain", 0),
    ("offre gratuite cliquez vite", 1),
    ("rapport du projet disponible", 0),
    ("vous avez gagné un cadeau", 1),
    ("merci pour votre retour", 0),

]
print("Jeu de données :")
for email, label in emails:
    print(label, "→", email)
print()
mots_cles = ["gratuit", "gagnez", "bonjour", "rapport"]
print("Mots observés :")
print(mots_cles)


Jeu de données :
1 → gagnez mille euros gratuit
0 → bonjour réunion demain
1 → offre gratuite cliquez vite
0 → rapport du projet disponible
1 → vous avez gagné un cadeau
0 → merci pour votre retour

Mots observés :
['gratuit', 'gagnez', 'bonjour', 'rapport']


In [ ]:
def email_vers_vecteur(email):
    email = email.lower()
    vecteur = []
    for mot in mots_cles:
        if mot in email:
            vecteur.append(1)
        else:
            vecteur.append(0)
    return vecteur

In [ ]:
email_spam = "félicitations vous avez gagné un cadeau gratuit"
email_normal = "bonjour le rapport est prêt"
print("Transformation d'un spam :")
print(email_spam)
print(email_vers_vecteur(email_spam))
print()
print("Transformation d'un email normal :")
print(email_normal)
print(email_vers_vecteur(email_normal))

Transformation d'un spam :
félicitations vous avez gagné un cadeau gratuit
[1, 0, 0, 0]

Transformation d'un email normal :
bonjour le rapport est prêt
[0, 0, 1, 1]


In [ ]:
X = np.array([email_vers_vecteur(email) for email, label in emails])
y = np.array([label for email, label in emails])
print("Matrice X :")
print(X)
print("Shape de X :", X.shape)
print()
print("Vecteur y :")
print(y)
print("Shape de y :", y.shape)

emails = [
    ("gagnez mille euros gratuit", 1),
    ("bonjour réunion demain", 0),
    ("offre gratuite cliquez vite", 1),
    ("rapport du projet disponible", 0),
    ("vous avez gagné un cadeau", 1),
    ("merci pour votre retour", 0),

]
["gratuit", "gagnez", "bonjour", "rapport"]

Matrice X :
[[1 1 0 0]
 [0 0 1 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]]
Shape de X : (6, 4)

Vecteur y :
[1 0 1 0 1 0]
Shape de y : (6,)


['gratuit', 'gagnez', 'bonjour', 'rapport']

In [ ]:
nouvel_email = "bonjour, voici le rapport gratuit"
vecteur_test = email_vers_vecteur(nouvel_email)

print("Nouvel email :")
print(nouvel_email)
print("Vecteur correspondant :")
print(vecteur_test)


Nouvel email :
bonjour, voici le rapport gratuit
Vecteur correspondant :
[1, 0, 1, 1]


In [ ]:
import numpy as np
quantites_liste = [3, 2, 5]
quantites = np.array([3, 2, 5])
print("Liste Python :", quantites_liste)
print("Type :", type(quantites))
print(quantites)
print()


Liste Python : [3, 2, 5]
Type : <class 'numpy.ndarray'>
[3 2 5]



In [ ]:
print("Avec une liste Python :")
print(quantites_liste * 2)
print("→ la liste est dupliquée")
print()
print("Avec un tableau NumPy :")
print(quantites * 2)
print("→ chaque élément est multiplié")


Avec une liste Python :
[3, 2, 5, 3, 2, 5]
→ la liste est dupliquée

Avec un tableau NumPy :
[ 6  4 10]
→ chaque élément est multiplié


In [ ]:
prix = np.array([0.50, 1.20, 0.80])
couts = quantites * prix
print("Quantités :", quantites)
print("Prix      :", prix)
print("Coûts     :", couts)


Quantités : [3 2 5]
Prix      : [0.5 1.2 0.8]
Coûts     : [1.5 2.4 4. ]


In [ ]:
total_manuel = couts[0] + couts[1] + couts[2]
total_dot = np.dot(quantites, prix)
print("Total manuel :", total_manuel)
print("Total np.dot :", total_dot)


Total manuel : 7.9
Total np.dot : 7.9


In [ ]:
print("Shape de quantites :", quantites.shape)
tableau_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print("Tableau 2D :")
print(tableau_2d)
print("Shape du tableau 2D :", tableau_2d.shape)


Shape de quantites : (3,)
Tableau 2D :
[[1 2 3]
 [4 5 6]]
Shape du tableau 2D : (2, 3)


In [ ]:
email_test = np.array([1, 1, 0, 0])
poids_exemple = np.array([0.8, 0.7, -0.2, -0.1])
score = np.dot(email_test, poids_exemple)
print("Email représenté par :", email_test)
print("Poids de chaque mot  :", poids_exemple)
print("Score du neurone     :", score)
print("Interprétation :")
print("présence des mots × poids → np.dot → score du neurone")


Email représenté par : [1 1 0 0]
Poids de chaque mot  : [ 0.8  0.7 -0.2 -0.1]
Score du neurone     : 1.5
Interprétation :
présence des mots × poids → np.dot → score du neurone


In [ ]:
import numpy as np
x = np.array([1, 1, 0, 0], dtype=float)
print("Vecteur de l'email :")
print(x)
print()
poids = np.array([0.9, 0.8, -0.6, -0.5])
biais = -0.2
print("Poids :")
print(poids)
print("Biais :", biais)


Vecteur de l'email :
[1. 1. 0. 0.]

Poids :
[ 0.9  0.8 -0.6 -0.5]
Biais : -0.2


In [ ]:
score = np.dot(x, poids) + biais
print("Score brut :")
print(score)


Score brut :
1.5000000000000002


In [ ]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))
probabilite = sigmoid(score)
print("Probabilité de spam :")
print(probabilite)


Probabilité de spam :
0.8175744761936437


In [ ]:
if probabilite >= 0.5:
    prediction = 1
else:
    prediction = 0
print("Prédiction numérique :")
print(prediction)
print()
if prediction == 1:
    print("Le neurone pense : spam")
else:
    print("Le neurone pense : email normal")


Prédiction numérique :
1

Le neurone pense : spam


In [ ]:
import numpy as np
mots_cles = ["gagnez", "gratuit", "bonjour", "rapport"]
poids = np.array([0.8, 0.7, -0.2, -0.1])
biais = -0.5
email_spam = np.array([1, 1, 0, 0])
email_normal = np.array([0, 0, 1, 1])


In [ ]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))
print("Comportement de la fonction sigmoid")
print("-" * 45)
for z_test in [-5, -2, 0, 2, 5]:
    proba = sigmoid(z_test)
    print(f"sigmoid({z_test:+}) = {proba:.4f}")


Comportement de la fonction sigmoid
---------------------------------------------
sigmoid(-5) = 0.0067
sigmoid(-2) = 0.1192
sigmoid(+0) = 0.5000
sigmoid(+2) = 0.8808
sigmoid(+5) = 0.9933


In [ ]:
def predire(email_vecteur):
    z = np.dot(email_vecteur, poids) + biais
    score = sigmoid(z)
    decision = "SPAM" if score > 0.5 else "NORMAL"
    return z, score, decision
for  email in [email_spam,email_normal]:
    z, score, decision = predire(email)
    print(z, round(score, 4), decision)


1.0 0.7311 SPAM
-0.8 0.31 NORMAL


In [ ]:
import numpy as np
def sigmoid(z):
    return 1 / (1 + np.exp(-z))
emails = np.array(
    [
        [1, 1, 0, 0],
        [0, 0, 1, 1],
        [1, 0, 1, 0]
    ]
)

In [ ]:
W1 = np.array([
    [ 0.9,  0.2, -0.3,  0.5],
    [ 0.9,  0.1, -0.2,  0.6],
    [-0.4,  0.8,  0.7, -0.1],
    [-0.3,  0.9,  0.6,  0.1],
], dtype=np.float64)
b1 = np.array([-0.8, -0.6, -0.4, -0.2], dtype=np.float64)
H = sigmoid(np.dot(emails, W1) + b1)
print("Sorties de la couche cachée H :")
print(np.round(H, 3))


Sorties de la couche cachée H :
[[0.731 0.426 0.289 0.711]
 [0.182 0.75  0.711 0.45 ]
 [0.426 0.599 0.5   0.55 ]]


In [ ]:
W2 = np.array([1.2, -0.9, -0.7, 0.8], dtype=np.float64)
b2 = -0.3
scores = sigmoid(np.dot(H, W2) + b2)
print("Prédictions finales :")
for i, score in enumerate(scores):
    decision = "SPAM" if score > 0.5 else "NORMAL"
    print(f"Email {i} -> score = {score:.3f} -> {decision}")


Prédictions finales :
Email 0 -> score = 0.637 -> SPAM
Email 1 -> score = 0.290 -> NORMAL
Email 2 -> score = 0.441 -> NORMAL


In [ ]:
import numpy as np
y = np.array([1, 0, 1])
predictions = np.array([0.92, 0.10, 0.20])
losses = (y - predictions) ** 2
print(losses)
print("loss moyenne =", losses.mean())


[0.0064 0.01   0.64  ]
loss moyenne = 0.21880000000000002


In [ ]:
modele_a = np.array([0.92, 0.10, 0.20])
modele_b = np.array([0.95, 0.05, 0.85])
loss_a = ((y - modele_a) ** 2).mean()
loss_b = ((y - modele_b) ** 2).mean()
print("loss modèle A =", round(loss_a, 3))
print("loss modèle B =", round(loss_b, 3))


loss modèle A = 0.219
loss modèle B = 0.009


In [ ]:
def binary_crossentropy(y, p):
    epsilon = 1e-12
    p = np.clip(p, epsilon, 1 - epsilon)
    return -(y * np.log(p) + (1 - y) * np.log(1 - p))
bce_losses = binary_crossentropy(y, modele_b)
print(bce_losses)
print("BCE moyenne =", bce_losses.mean())


[0.05129329 0.05129329 0.16251893]
BCE moyenne = 0.0883685060909587


In [ ]:
import numpy as np
def sigmoid(z):
    return 1 / (1 + np.exp(-z))
def loss_pour_poids_gratuit(w):
    email = np.array([1, 1, 0, 0])
    y = 1
    poids = np.array([0.9, w, -0.6, -0.5])
    biais = -0.2
    score = np.dot(email, poids) + biais
    prediction = sigmoid(score)
    loss = (y - prediction) ** 2
    return loss
w = 0.40
print("loss actuelle =", loss_pour_poids_gratuit(w))


loss actuelle = 0.062370014857361766


In [ ]:
epsilon = 0.01
loss_actuelle = loss_pour_poids_gratuit(w)
loss_plus = loss_pour_poids_gratuit(w + epsilon)
gradient = (loss_plus - loss_actuelle) / epsilon
print("loss si w augmente légèrement =", loss_plus)
print("gradient approximatif =", gradient)


loss si w augmente légèrement = 0.06143997739573702
gradient approximatif = -0.0930037461624747


In [ ]:
learning_rate = 0.5
nouveau_w = w - learning_rate * gradient
print("ancien poids =", w)
print("nouveau poids =", nouveau_w)
print("ancienne loss =", loss_pour_poids_gratuit(w))
print("nouvelle loss =", loss_pour_poids_gratuit(nouveau_w))


ancien poids = 0.4
nouveau poids = 0.44650187308123734
ancienne loss = 0.062370014857361766
nouvelle loss = 0.05814300662360455


In [ ]:
import numpy as np
emails = [
    ("gagnez un cadeau gratuit", 1),
    ("bonjour voici le rapport", 0),
    ("urgent gratuit gagnez maintenant", 1),
    ("bonjour reunion rapport projet", 0),
]
mots_cles = ["gratuit", "gagnez", "bonjour", "rapport"]

def email_vers_vecteur(email):
    email = email.lower()
    vecteur = []
    for mot in mots_cles:
        if mot in email:
            vecteur.append(1)
        else:
            vecteur.append(0)
    return np.array(vecteur, dtype=float)
X = np.array([email_vers_vecteur(e) for e, label in emails])
y = np.array([label for e, label in emails], dtype=float)
print(X)
print(y)
def sigmoid(z):
    return 1 / (1 + np.exp(-z))
poids = np.array([0.1, 0.1, -0.1, -0.1])
biais = 0.0
def predire(x):
    score = np.dot(x, poids) + biais
    return sigmoid(score)
print(predire(X[0]))




[[1. 1. 0. 0.]
 [0. 0. 1. 1.]
 [1. 1. 0. 0.]
 [0. 0. 1. 1.]]
[1. 0. 1. 0.]
0.549833997312478


In [ ]:
learning_rate = 0.5
epsilon = 0.01


epochs = 30
for epoch in range(epochs):
    loss_totale = 0
    for i in range(len(X)):
        x = X[i]
        vraie_reponse = y[i]
        prediction = predire(x)
        loss_actuelle = (vraie_reponse - prediction) ** 2
        loss_totale += loss_actuelle
        gradients_poids = np.zeros_like(poids)
        for j in range(len(poids)):
            poids_temp = poids.copy()
            poids_temp[j] = poids_temp[j] + epsilon
            prediction_plus = sigmoid(np.dot(x, poids_temp) + biais)
            loss_plus = (vraie_reponse - prediction_plus) ** 2
            gradients_poids[j] = (loss_plus - loss_actuelle) / epsilon
        biais_plus = biais + epsilon
        prediction_plus_biais = sigmoid(np.dot(x, poids) + biais_plus)
        loss_plus_biais = (vraie_reponse - prediction_plus_biais) ** 2
        gradient_biais = (loss_plus_biais - loss_actuelle) / epsilon
        poids = poids - learning_rate * gradients_poids
        biais = biais - learning_rate * gradient_biais
    if epoch % 5 == 0:
      print("epoch =", epoch, "loss totale =", loss_totale)


epoch = 0 loss totale = 0.7597255951085706
epoch = 5 loss totale = 0.13920341071477318
epoch = 10 loss totale = 0.0680105385932087
epoch = 15 loss totale = 0.04394084309208637
epoch = 20 loss totale = 0.03215207867413046
epoch = 25 loss totale = 0.025229647456898176


In [ ]:
print("Poids appris :", poids)
print("Biais appris :", biais)
for email, label in emails:
    x = email_vers_vecteur(email)
    proba = predire(x)
    if proba >= 0.5:
        classe = "spam"
    else:
        classe = "normal"
    print(email, "=>", round(proba, 3), classe)


Poids appris : [ 1.27502741  1.27502741 -1.27987201 -1.27987201]
Biais appris : -0.004844591655814778
gagnez un cadeau gratuit => 0.927 spam
bonjour voici le rapport => 0.071 normal
urgent gratuit gagnez maintenant => 0.927 spam
bonjour reunion rapport projet => 0.071 normal


In [ ]:
import numpy as np
import keras
from keras import layers
emails = [
    ("gagnez un cadeau gratuit", 1),
    ("bonjour voici le rapport", 0),
    ("urgent gratuit gagnez maintenant", 1),
    ("bonjour reunion rapport projet", 0),
]
mots_cles = ["gratuit", "gagnez", "bonjour", "rapport"]
def email_vers_vecteur(email):
    email = email.lower()
    return [1 if mot in email else 0 for mot in mots_cles]
X = np.array([email_vers_vecteur(e) for e, label in emails], dtype="float32")
y = np.array([label for e, label in emails], dtype="float32")
print("X =")
print(X)
print("y =", y)
print("shape de X :", X.shape)
print("shape de y :", y.shape)
model = keras.Sequential(
    [
        layers.Input(shape=(4,)),
        layers.Dense(1, activation="sigmoid")

    ]
)
model.summary()
model.compile(
    optimizer=keras.optimizers.SGD(learning_rate=0.5),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)
history = model.fit(
    X,
    y,
    epochs=100,
    verbose=0
)
print("Entraînement terminé")
for email, label in emails:
    x = np.array([email_vers_vecteur(email)], dtype="float32")
    proba = model.predict(x, verbose=0)[0][0]
    classe = "spam" if proba >= 0.5 else "normal"
    print(email, "=>", round(float(proba), 3), classe)

nouvel_email = "gratuit gagnez maintenant"
x = np.array([email_vers_vecteur(nouvel_email)], dtype="float32")
proba = model.predict(x, verbose=0)[0][0]
classe = "spam" if proba >= 0.5 else "normal"
print("Nouvel email :", nouvel_email, "=>", round(float(proba), 3), classe)


X =
[[1. 1. 0. 0.]
 [0. 0. 1. 1.]
 [1. 1. 0. 0.]
 [0. 0. 1. 1.]]
y = [1. 0. 1. 0.]
shape de X : (4, 4)
shape de y : (4,)


Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_5 (Dense)                 │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5 (20.00 B)

 Trainable params: 5 (20.00 B)

 Non-trainable params: 0 (0.00 B)

Entraînement terminé
gagnez un cadeau gratuit => 0.98 spam
bonjour voici le rapport => 0.02 normal
urgent gratuit gagnez maintenant => 0.98 spam
bonjour reunion rapport projet => 0.02 normal
Nouvel email : gratuit gagnez maintenant => 0.98 spam
