In [32]:
import numpy as np
import torch
x_numpy = np.array([1, 1, 0, 0])
x_tensor = torch.tensor([1, 1, 0, 0],dtype=torch.float32)
print(x_numpy)
print(x_tensor)

[1 1 0 0]
tensor([1., 1., 0., 0.])


In [33]:
import torch
a = torch.tensor([1, 2, 3], dtype=torch.float32)
b = torch.zeros((2, 3))
c = torch.ones((2, 2))
d = torch.arange(0, 10)
e = torch.randn((2, 3))
print(a)
print(b)
print(c)
print(d)
print(e)



tensor([1., 2., 3.])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[ 1.8158, -0.0093, -2.3605],
        [-0.9269, -1.3941,  0.0757]])


In [34]:
x = torch.tensor([1, 1, 0, 0],
                 dtype=torch.float32)

X = torch.tensor([
    [1, 1, 0, 0],
    [0, 0, 1, 1],
    [1, 0, 1, 0]
], dtype=torch.float32)

print(x.shape)   # torch.Size([4])
print(X.shape)   # torch.Size([3, 4])

torch.Size([4])
torch.Size([3, 4])


In [35]:
X = torch.tensor([
    [1, 1, 0, 0],
    [0, 0, 1, 1],
    [1, 0, 1, 0]
], dtype=torch.float32)

print(X[0])      # première ligne
print(X[1])      # deuxième ligne
print(X[:, 0])   # première colonne
print(X[2, 3])   # valeur ligne 3, colonne 4

tensor([1., 1., 0., 0.])
tensor([0., 0., 1., 1.])
tensor([1., 0., 1.])
tensor(0.)


In [36]:
x = torch.tensor([1, 1, 0, 0])
print(x.dtype)

x = x.float()
print(x.dtype)

x_numpy = x.numpy()
print(type(x_numpy))

x2 = torch.tensor(x_numpy, dtype=torch.float32)
print(type(x2))


torch.int64
torch.float32
<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [37]:
x = torch.arange(1, 13)
print(x)
print(x.shape)

A = x.reshape(3, 4)
print(A)
print(A.shape)

B = A.view(2, 6)
print(B)
print(B.shape)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
torch.Size([12])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
torch.Size([3, 4])
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])
torch.Size([2, 6])


In [38]:
import torch
X = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
], dtype=torch.float32)
print(X)
print("shape =", X.shape)
X2 = X.unsqueeze(0)
print(X2)
print("shape =", X2.shape)
X3 = X.unsqueeze(1)
print(X3)
print("shape =", X3.shape)
X4 = X.unsqueeze(2)
print(X4)
print("shape =", X4.shape)
X5 = X4.squeeze()
print(X5)
print("shape =", X5.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
shape = torch.Size([3, 3])
tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])
shape = torch.Size([1, 3, 3])
tensor([[[1., 2., 3.]],

        [[4., 5., 6.]],

        [[7., 8., 9.]]])
shape = torch.Size([3, 1, 3])
tensor([[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]],

        [[7.],
         [8.],
         [9.]]])
shape = torch.Size([3, 3, 1])
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
shape = torch.Size([3, 3])


In [39]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

print(torch.stack([a, b], dim=0))
# [[1, 2, 3],
#  [4, 5, 6]]

print(torch.cat([a, b], dim=0))
# [1, 2, 3, 4, 5, 6]


tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([1, 2, 3, 4, 5, 6])


In [40]:
x = torch.tensor([1., 1., 0., 0.])
w = torch.tensor([0.9, 0.8, -0.6, -0.5])

print(x + w)
print(x - w)
print(x * w)

score1 = torch.sum(x * w)
score2 = torch.dot(x, w)

print(score1)
print(score2)


tensor([ 1.9000,  1.8000, -0.6000, -0.5000])
tensor([0.1000, 0.2000, 0.6000, 0.5000])
tensor([0.9000, 0.8000, -0.0000, -0.0000])
tensor(1.7000)
tensor(1.7000)


In [41]:
X = torch.tensor([
    [1., 1., 0., 0.],
    [0., 0., 1., 1.]
])

W = torch.tensor([
    [0.9],
    [0.8],
    [-0.6],
    [-0.5]
])

scores = torch.matmul(X, W)
print(scores)
print(scores.shape)


tensor([[ 1.7000],
        [-1.1000]])
torch.Size([2, 1])


In [42]:
w = torch.tensor(0.4, requires_grad=True)
x = torch.tensor(1.0)
y = torch.tensor(1.0)

prediction = torch.sigmoid(x * w)
loss = (y - prediction) ** 2

loss.backward()

print(loss)
print(w.grad)


tensor(0.1611, grad_fn=<PowBackward0>)
tensor(-0.1928)


In [43]:
X = torch.tensor([
    [1, 1, 0, 0],
    [0, 0, 1, 1],
    [1, 0, 1, 0],
    [0, 1, 0, 1]
], dtype=torch.float32)

y = torch.tensor([1, 0, 1, 0],
                 dtype=torch.float32).unsqueeze(1)

print(X.shape)   # [4, 4]
print(y.shape)   # [4, 1]


torch.Size([4, 4])
torch.Size([4, 1])
